Repository booru/philomena, pull requests merged in 2020-08, with the labels that each got.

#49 Remove duplicate SMTP_ env var entries
  docker-compose.yml
Labels: bug

#48 Increase logo size to 2em
  assets/css/common/_base.scss
Labels: enhancement

#51 Re-add name length and notable plugs to registration controller.
  lib/philomena_web/controllers/registration_controller.ex
Labels: bug

#52 Multiple email-related fixes.
  .env.example
  docker-compose.yml
  lib/philomena/application.ex
  lib/philomena_web/plugs/dev_only_plug.ex
  lib/philomena_web/router.ex
Labels: bug, enhancement

#50 Fix ad caption
  lib/philomena_web/templates/advert/_box.html.slime
Labels: bug

#61 adjust image uploaded wait message as requested
  lib/philomena_web/templates/image/_image_page.html.slime
Labels: enhancement

#63 Hide Emails
  lib/philomena_web/templates/admin/user/index.html.slime
  lib/philomena_web/views/admin/user_view.ex
Labels: enhancement

#64 Bold links in forum/convo/comment message body.
  assets/css/common/_base.scss
Labels: enhancement

#65 Disable anon reports, site-wide.
  lib/philomena/users/ability.ex
  lib/philomena_web/controllers/conversation/report_controller.ex
  lib/philomena_web/controllers/duplicate_report_controller.ex
  lib/philomena_web/controllers/gallery/report_controller.ex
  lib/philomena_web/controllers/image/comment/report_controller.ex
  lib/philomena_web/controllers/image/report_controller.ex
  lib/philomena_web/controllers/profile/commission/report_controller.ex
  lib/philomena_web/controllers/profile/report_controller.ex
  lib/philomena_web/controllers/topic/post/report_controller.ex
  lib/philomena_web/plugs/authorized_reporter_plug.ex
  lib/philomena_web/templates/comment/_comment_options.html.slime
  lib/philomena_web/templates/gallery/show.html.slime
  lib/philomena_web/templates/image/_options.html.slime
  lib/philomena_web/templates/post/_post_options.html.slime
  lib/philomena_web/templates/profile/commission/_listing_sidebar.html.slime
  lib/philomena_web/templates/profile/show.html.slime
  lib/philomena_web/views/comment_view.ex
  lib/philomena_web/views/conversation_view.ex
  lib/philomena_web/views/gallery_view.ex
  lib/philomena_web/views/image/comment_view.ex
  lib/philomena_web/views/image_view.ex
  lib/philomena_web/views/post_view.ex
  lib/philomena_web/views/profile/commission_view.ex
  lib/philomena_web/views/profile_view.ex
  lib/philomena_web/views/topic/post_view.ex
Labels: enhancement

#74 fix twitter scraper
  lib/philomena/scrapers/twitter.ex
Labels: bug

#62 Limit length of tag names
  lib/philomena/tags.ex
  lib/philomena/tags/tag.ex
Labels: enhancement

#81 Add filtering for already processed images
  lib/philomena/images/elasticsearch_index.ex
  lib/philomena/images/query.ex
  lib/philomena/workers/thumbnail_worker.ex
  lib/philomena_web/controllers/activity_controller.ex
  lib/philomena_web/controllers/image_controller.ex
Labels: enhancement
